services:
  database:
    image: postgres
    container_name: beausys-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: beausys
    ports:
      - "5432:5432"
