name: Beausys Ci

# Moment to run the workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use node.js 22x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm ci

      - name: Typechecking
        run: npm run typecheck

      - name: Jest test
        run: npm run test
